# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hotel-app
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hotel-app
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005
  type: NodePort
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: hotel-app
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017  #added
    targetPort: 27017
  type: ClusterIP
