name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Backend Docker image
      run: |
        docker build -t abdullah856/my-app-backend:latest -f backend.Dockerfile .

    - name: Build Frontend Docker image
      run: |
        docker build -t abdullah856/my-app-frontend:latest -f frontend.Dockerfile .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Backend Docker image to Docker Hub
      run: docker push abdullah856/my-app-backend:latest

    - name: Push Frontend Docker image to Docker Hub
      run: docker push abdullah856/my-app-frontend:latest

    - name: Deployto Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

